SHOW DATABASES;
USE LIBRARY;
SHOW TABLES;
SELECT * FROM USER;

CREATE TABLE USER (
    ID CHAR(36) PRIMARY KEY,
    USERNAME VARCHAR(80) NOT NULL,
    PASSWORD VARCHAR(80) NOT NULL,
    ROLE VARCHAR(40) NOT NULL DEFAULT 'ROLE_USER',
    SIGNUP_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 임의 데이터 삽입
-- INSERT INTO USER (PRIVATE_ID, ID, PW, GRADE) VALUES (UUID(), '관리자', 'admin1', 9);
-- INSERT INTO USER (PRIVATE_ID, ID, PW) VALUES (UUID(), '테스트1', 'test1');
-- INSERT INTO USER (PRIVATE_ID, ID, PW) VALUES (UUID(), '테스트2', 'test2');
-- INSERT INTO USER (PRIVATE_ID, ID, PW) VALUES (UUID(), '테스트3', 'test3');
-- INSERT INTO USER (PRIVATE_ID, ID, PW) VALUES (UUID(), '테스트4', 'test4');
DELETE FROM USER WHERE PRIVATE_ID = '';

SELECT * FROM USER;
